### PR TITLE
feat: add support for implicit React imports

### LINKED ISSUE #20: Allow implicit React import?
Since [JSX-Transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html), I have not used to importing React explicitly in my codebases. I want to treat the same with my code blocks i.e. I want to configure so that React is imported implicitly in my `tsx` code blocks.

errrrrr

Currently, I think best I can do is to cut imports like,

```tsx
import React from 'react'
// ---cut---
```

But I don't think it's the best option. Or am I missing something?

### PR DESCRIPTION
**Pull request by frencojobs**
Closes #20

### CODE REVIEW

**Comment by frencojobs** [comment]
Oops. What happened?

**Comment by orta** [comment]
Unsure, that's doubled the time of the normal test run on CI - ran out of personal time to dig into it

**Comment by frencojobs** [comment]
Yay! It worked.

I think recent shiki release hurt their performance a bit. Feel free to increase the jest's timeOut if you want to keep it up with the latest version. I lowered them down to `v0.9.3`.

**Comment by orta** [comment]
Nice, nah this is fine for now - good work!

**Pull request merged**
